# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build_Windows
    displayName: Build
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: GitVersion@5
      displayName: 'Get Version Number'
      inputs:
        runtime: 'core'
        configFilePath: 'gitversion.yml'
  
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: 
    
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'select'
        vstsFeed: 'e745086d-201a-4e45-8d8f-ed7088052af8'
        restoreDirectory: 'NugetPackage'

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/Service/Wallpaper.Service/Dockerfile'
        tags: |
          $(tag)
    
    - task: Docker@2
      displayName: Push the image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'jasase/wallpaper.service'
        command: 'push'
        tags: |
          $(GitVersion.NuGetVersionV2)
          latest